version: "3.9"

x-vol:
  &vol
  type: bind
  bind:
    propagation: rshared
  source: ../appdata
  target: /media

services:
  frontend:
    build:
      context: ./mi_tv_frontend
      args:
        BACKEND_URL: http://127.0.0.1:5000 #https://portail-etu.emse.fr/mitv/api/ # http://127.0.0.1:5000
        FRONTEND_URL: http://127.0.0.1:5173 #https://portail-etu.emse.fr/mitv/ # http://127.0.0.1:5173
    ports:
      - "5173:5173"

  backend:
    build: ./mi_tv_backend
    ports:
      - "5000:5000"
    volumes:
      - *vol

  media-processor:
    build: ./mi_tv_backend/image_metadata
    volumes:
      - *vol

  database:
    image: "mongo:6"
    ports:
      - "27017:27017"
    volumes:
      - /data/db