version: "3.9"

x-vol:
  &vol
  type: bind
  bind:
    propagation: rshared
  source: ../appdata
  target: /media

services:
  frontend:
    build:
      context: ./mi_tv_frontend
      args:
        BACKEND_URL: https://portail-etu.emse.fr/mitv/api/
        FRONTEND_URL: https://portail-etu.emse.fr/mitv/
    ports:
      - "5173:5173"

  backend:
    build: ./mi_tv_backend
    ports:
      - "5000:5000"
    volumes:
      - *vol

  media-processor:
    build: ./mi_tv_backend/image_metadata
    volumes:
      - *vol

  database:
    image: "mongo:6"
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongodb_data_volume
        target: /data/db

volumes:
  mongodb_data_volume:
    external: true